app/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # Admin URLs
path("home/admin", AdminHomeView.as_view(), name="admin-home"),
path("register/admin", AdminRegistrationView.as_view(), name="admin-registration"),
path('login/admin', AdminLoginView.as_view(), name='admin-login'),
path('add/locations', AddLocationView.as_view(), name="add-locations"),
path('approval/<int:pk>', approve_mechanic, name="approve"),
path('location-delete/<int:pk>', locationdelete, name="locdel"),

# Mechanic URLs
path("mechanic/home", MechnaicHomeView.as_view(), name="mechanic_home"),
path("add/profile/<int:pk>", MechanicProfileAddView.as_view(), name="add-profile"),
path("profile/view/<int:pk>", MechanicProfileDetailView.as_view(), name="view-profile"),
path("profile/<int:pk>/update", MechanicprofileUpdateView.as_view(), name="update-profile"),
path('pending', PendingMechanicView.as_view(), name="pending-list"),
path('my-requests/', MechanicReqListView.as_view(), name='mechanic_requests'),
path('mechanicapproval/<int:pk>', update_status, name="mech-approve"),
path('feedback-list/', FeedbackListView.as_view(), name='feedback_list'),
path('create-bill-payment/<int:pk>/', BillPaymentCreateView.as_view(), name='create_bill_payment'),


# User URLs
path("user/home", UserHomeView.as_view(), name="user_home"),
path("user/registration", RegistrationView.as_view(), name="user_registration"),
path("useradd/profile/<int:pk>", UserProfileAddView.as_view(), name="useradd-profile"),
path("userprofile/view/<int:pk>", UserProfileDetailView.as_view(), name="userview-profile"),
path("userprofile/update/<int:pk>", UserProfileUpdateView.as_view(), name="userupdate-profile"),
path('approved-mechanics/', ApprovedMechanicListView.as_view(), name='approved_mechanics'),
path("create/req/<int:mechanic_id>", ReqToMechanicCreateView.as_view(), name="create_req"),
path('requests/', UserRequestsListView.as_view(), name='user_requests'),
path('feedback/<int:pk>/', FeedBackCreateView.as_view(), name='feedback_form'),
path('bill-payment/<int:pk>/', bil_payment, name='bill_payment'),
path('cars/available/', RentCarListView.as_view(), name='available_cars'),
path('reserve/<int:pk>/', ReserveCarView.as_view(), name='reserve_car'),
path('reservations/', UserReservationListView.as_view(), name='user_reservation_list'),
path('update_reservation/<int:pk>/',update_reservation, name='update_reservation'),
path('userpayment/<int:pk>/',UserPaymentDetailsView.as_view(), name='user_payment'),
path('userpaymentdetails/<int:pk>/',UserPaymentView.as_view(), name='payment_details'),
path('mechanichistory/<int:pk>/',MechanicHistory.as_view(), name='mechistory'),

#car renter URLS
path("car/home", CarRenterHomeView.as_view(), name="car_home"),
path('car_renter_profile/<int:pk>', CarRenterProfileCreateView.as_view(), name='car_renter_profile'),
path('car_renter_profile/update/<int:pk>', CarRenterProfileUpdateView.as_view(), name='car_renter_profile_update'),
path('car_renter_profile/view/', CarRenterProfileDetailView.as_view(), name='car_renter_profile_view'),
path('rent_car/', RentCarCreateView.as_view(), name='rent_car_create'),
path('rent_car/update/<int:pk>/', RentCarUpdateView.as_view(), name='rent_car_update'),
path('rentcars/', UserRentCarListView.as_view(), name='rentcar_list'),
path('my_reservations/', CarOwnerReservationsListView.as_view(), name='car_owner_reservations'),

# path('reservation/<int:pk>', ReservationDetailView.as_view(), name='reservation_detail'),


# Common URLs
path("",HomeView.as_view(),name="home"),
path('login/', LoginView.as_view(), name='login'),
path('logout/', LogoutView, name='logout'), 
path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
path("payment/sucess/",PaymentSuccessView.as_view(),name="payment"),
path('search/',mechanic_search, name='mechanic_search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Location(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name

class User(AbstractUser):
    ROLE_CHOICES = [
        ("admin","Admin"),
        ("user", "User"),
        ("mechanic", "Mechanic"),
        ("car_renter","Car Renter")
    ]
    role = models.CharField(max_length=200, choices=ROLE_CHOICES, default="user")

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    name=models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    dob = models.DateField(null=True)
    profile_pic = models.ImageField(upload_to="userprofile",default='static/images/profile/default.jpg', blank=True, null=True)

    def __str__(self):
        return self.user.username


class MechanicProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="mechanic_profile")
    name=models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name="mechanic_location")
    phone = models.CharField(max_length=200)
    dob = models.DateField(null=True)
    skills = models.TextField()
    experience = models.CharField(max_length=200)
    STATUS_CHOICES = [
        ("approved", "Approved"),
        ("pending", "Pending"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="pending")
    SPECIALIZATION_CHOICES = [
        ("two_wheeler", "Two Wheeler"),
        ("four_wheeler", "Four Wheeler"),
        ("heavy_vehicle", "Heavy Vehicle"),
    ]
    specialized_in = models.CharField(max_length=200, choices=SPECIALIZATION_CHOICES)
    bio = models.CharField(max_length=200)
    profile_pic = models.ImageField(upload_to="mech_pics",default='static/images/profile/default.jpg', blank=True, null=True)

    def __str__(self):
        return self.user.username


class ReqToMechanic(models.Model):
    user=models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name="req_profile")
    mechanic=models.ForeignKey(MechanicProfile,on_delete=models.CASCADE,related_name="req_profile")
    discription=models.CharField(max_length=200)
    phone=models.IntegerField()
    location=models.ForeignKey(Location,on_delete=models.CASCADE,related_name="req_location")
    STATUS_CHOICES = [
        ("completed", "Completed"),
        ("Payment Pending", "Payment Pending"),
        ("pending", "Pending"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="pending")
    datetime=models.DateTimeField(auto_now_add=True,null=True)


class Bill(models.Model):
    customer=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    mechanic=models.ForeignKey(MechanicProfile,on_delete=models.CASCADE)
    req=models.ForeignKey(ReqToMechanic,on_delete=models.CASCADE)
    payment=models.PositiveBigIntegerField()
    STATUS_CHOICES = [
        ("completed", "Completed"),
        ("pending", "Pending"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="pending")


class UserPayment(models.Model):
    customer=models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name='cust_pay')
    mechanic=models.ForeignKey(MechanicProfile,on_delete=models.CASCADE,related_name='mech_pay')
    req=models.ForeignKey(ReqToMechanic,on_delete=models.CASCADE,related_name='user_pay')
    acholdername=models.CharField(max_length=100)
    accno=models.PositiveBigIntegerField()
    cvv=models.IntegerField()
    exp=models.CharField(max_length=100)
    amount=models.PositiveBigIntegerField()
    
    def __str__(self):
        return self.acholdername


class FeedBack(models.Model):
    user=models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name="feedback_userprofile")
    request=models.ForeignKey(ReqToMechanic,on_delete=models.CASCADE,related_name="feedback_req",null=True)
    mechanic=models.ForeignKey(MechanicProfile,on_delete=models.CASCADE,related_name="feedback_mechanicprofile")
    text=models.CharField(max_length=200)
    options=(
        ("1","1"),
        ("2","2"),
        ("3","3"),
        ("4","4"),
        ("5","5"),
    )
    rating=models.CharField(max_length=200,choices=options,default="5")
    date=models.DateTimeField(auto_now_add=True)

class CarRenterProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="carrental_profile")
    name=models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    dob = models.DateField(null=True)
    bio = models.CharField(max_length=200)
    profile_pic = models.ImageField(upload_to="pic_pics",default='static/images/profile/default.jpg', blank=True, null=True)

    def __str__(self):
        return self.user.username

class RentCar(models.Model):
    owner=models.ForeignKey(CarRenterProfile,on_delete=models.CASCADE,related_name="carrental_profile")
    name=models.CharField(max_length=200)
    price=models.PositiveBigIntegerField()
    car_img=models.ImageField(upload_to="car_pics",default='static/images/car/default.jpg', blank=True, null=True)
    discription=models.CharField(max_length=200)
    STATUS_CHOICES = [
        ("available", "Available"),
        ("not_available", "Not Available"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="available")
    def __str__(self):
        return self.name

class CarReserve(models.Model):
    customer=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    car=models.ForeignKey(RentCar,on_delete=models.CASCADE)
    start_date=models.DateField()
    end_date=models.DateField()
    checked_out = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    class Meta:
        ordering = ['-created_on']

app/templates/add_location.html
{% extends 'admin_home.html' %}
{% block dashboard %}
<style>
     .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 40vh;
            padding: 30px;
        }
</style>
                <div class="container">
                    <form class="form-control   shadow" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="text-center">
                            <span class="h2 fw-bold">ADD LOCATION</span>
                        </div>
                        <div class="mt-4 mb-4">
                            <input class="form-control" placeholder="Enter Location" type="text" name="name" id="">
                        </div>
                        <div class="text-center mb-3 mt-3">
                            <button class="btn btn-primary mt-3">Add</button>
                            <button class="btn btn-danger mt-3">Cancel</button>
                        </div>
                    </form> 
                  
                </div>
                <div class="row " style="padding: 20px;overflow: scroll;height: 390px;">
                    {% for location in loc %}
                    
                            <div class="card mb-1" style="padding: 20px;">
                                <span>{{forloop.counter}} . {{location.name}}<a href="{% url 'locdel' location.id %}" class="btn btn-danger" style="float: right;">Delete</a></span>
                            </div>
                          
                    {% endfor %}
                </div>
 {% endblock   %}

app/templates/admin_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    
</head>

<body>
    <section>

        <div class="box">

            <div class="square" style="--i:0;"></div>
            <div class="square" style="--i:1;"></div>
            <div class="square" style="--i:2;"></div>
            <div class="square" style="--i:3;"></div>
            <div class="square" style="--i:4;"></div>
            <div class="square" style="--i:5;"></div>

            <div class="container">
                <div class="form">
                    <h2 class="text align-items-center">Admin Login</h2>
                    <form action="" method="post">
                        {%csrf_token%}
                        <div class="inputBx">
                            <input name="username" type="text" required="required">
                            <span>Username</span>
                            <i class="fas fa-user-circle"></i>
                        </div>
                        <div class="inputBx password">
                            <input id="password-input" type="password" name="password" required="required">
                            <span>Password</span>
                            <a href="#" class="password-control" onclick="return show_hide_password(this);"></a>
                            <i class="fas fa-key"></i>
                        </div>
                        <label class="remember"><input type="checkbox">
                            Remember</label>
                        <div class="inputBx">
                            <input type="submit" value="Log in">
                        </div>
                        <script>
    document.addEventListener('DOMContentLoaded', function () {
        {% if messages %}
            {% for message in messages %}
                alert({{ form.errors }});
            {% endfor %}
        {% endif %}
    });
  </script>
                    </form>
                    <p>Forgot password? <a href="#">Click Here</a></p>
                    <p>Don't have an account <a href="{%url 'admin-registration'%}">Sign up</a></p>
                </div>
            </div>

        </div>
    </section>

</body>
<script src="{% static 'js/login.js'%}"></script>

</html>

app/templates/approved_mechanic.html
{% extends 'user_home.html' %}
{% block user %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha384-k6RqeWeci5ZR/Lv4MR0sA0FfDOM6S5y3mQKk6t2R0wE7t6k4Gx8QQoF5WzDcp5A" crossorigin="anonymous">

<style>
    body{
        background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(76, 76, 77) 100%);
    }
</style>
    <div class="container mt-5">
        <div class="text-center my-3 text-white" style="font-family: 'Times New Roman', Times, serif;font-weight: bolder;">
            <h1 style="margin-left:320px;"> MECHANICS<form method="get" action="{% url 'approved_mechanics' %}" style="float: right;">
              <input type="text" name="search" value="{{ search_query }}" style="width:250px;height:40px;border-radius:0.5rem;">
              <button type="submit" style=" border-radius: 0.2rem; margin-left: 2px;background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(76, 76, 77) 100%);">
                <svg  xmlns="http://www.w3.org/2000/svg" height="35" width="35" style="padding:5px ;background-color:white;margin-bottom:8px;border-radius:0.2rem;margin-left:2px;" viewBox="0 0 512 512"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path fill="#050505" d="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352a144 144 0 1 0 0-288 144 144 0 1 0 0 288z"/></svg>
              </button>
          </form></h1>
        </div>
    <!-- <ul>
        {% for mechanic in mechanics %}
        <li>{{ mechanic.name }}</li>
        <form action="{%url 'create_req' mechanic.id %}" method="post">
            {%csrf_token%}
            <button type="submit">Request</button>
        </form>
        {% endfor %}
    </ul> -->


        <div class="row">
            {% for mechanic in mechanics %}
  
             <div class="col-sm-6 mb-3 mb-sm-0 g-3  ">
             <a href="{% url 'mechistory' mechanic.id %}" style="text-decoration: none;">
          <div class="col-lg-3">
            <img src="{{ mechanic.profile_pic.url }}" class="card-img-top ml-1" style="margin-top: 20%;" alt="..." height="500px" width="120px">
          </div>
          <div class="col" >
            <div class="card-body">
              <h2 class="card-title" style="font-family: 'Courier New', Courier, monospace;font-weight: bold;">{{mechanic.name}}</h2>
          
            </div>
          </a>
            <ul class="list-group list-group-flush" style="border-radius: 0.75rem;">
              <li class="list-group-item mr-2 jumbotron" >Location <span style="margin-left: 100px;" >:</span>&nbsp;&nbsp;{{mechanic.location}}</li>
    
              <li class="list-group-item mt-2 mr-2">Phone <span style="margin-left: 115px;">:</span>&nbsp;&nbsp;{{mechanic.phone}}</li>
              <li class="list-group-item mt-2 mr-2">Skills <span style="margin-left: 125px;">:</span>&nbsp;&nbsp;{{mechanic.skills}}</li>
              <li class="list-group-item mt-2 mr-2">Experience <span style="margin-left: 85px;">:</span>&nbsp;&nbsp;{{mechanic.experience}}</li>
             
            </ul>

             <div class="row mt-2 mr-1 ml-1 mb-2">
                        <div class="col-4"></div>
              <div class="col">  <form action="{%url 'create_req' mechanic.id %}"   >
                {% csrf_token %}
                <button  type="submit" class="btn btn-info text-white">Send Request</button>
                
            </form>
                </div>
             <div class="col-1"></div>
            </div>
            
          </div>
          </div>
      
            {% endfor %}
        </div>
    </div>
{% endblock %}

app/templates/car_renter_register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CarRenter Registeration</title>
</head>

<body>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Register</button>
    </form>
</body>

</html>

app/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORVBA </title>
    <link rel="stylesheet" href="{% static 'css/navbar.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary  ">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png' %}" alt="logo" srcset="" width="150">
        </a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <div class="d-flex gap-3 ms-auto me-3 cont">
                <div class="nav-item it">
                    <a class="nav-link" href="">Home</a>
                </div>
                <!-- <div class="nav-item it">
                    <a class="nav-link" href="">Shop</a>
                </div> -->
                <div class="it nav-item">
                    <a class="nav-link" href="{%url 'admin-login'%}">Admin Login</a>
                </div>
                <div class="it nav-item">
                    <a class="nav-link" href="{%url 'login'%}">Login</a>
                </div>
            </div>
        </div>
    </div>
</nav>
<div class="container-fluid  m-0 p-0">
    <div class="img-container container-fluid  m-0 p-0">
        <img src="{% static 'images/banner.jpg' %}" alt="Image" class="img img-fluid m-0 p-0" width="100%" style="height:638px;">
        <div class="text-overlay">
            <h1 text-bold>ONROAD VEHICLE BREAKDOWN ASSISTANCE</h1>
        </div>
    </div>
</div>
</body>
</html>

app/templates/mechanic_changepassword.html
{% extends 'mechanic_home.html' %}
{% block  mechanic %}
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<!-- Add Bootstrap JavaScript (optional, but required for certain features) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<style>
    body{
        background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(76, 76, 77) 100%);
    }

        .main-content {
            flex: 1;
            padding: 20px;
        }

        .dashboard-heading {
            text-align: center;
            color: #fff;
            margin-bottom: 30px;
        }

        .dashboard-item {
            margin-bottom: 20px;
        }

        .dashboard-item a {
            color: #fff;
            text-decoration: none;
            display: block;
            padding: 10px;
            border-radius: 5px;
        }

        .dashboard-item a:hover {
            background-color: #495057;
        }

        .card {
            border: none;
            border-radius: 10px;
            box-shadow: 0px 0px 20px rgba(0, 0, 0, 0.1);
            width:700px;
        }

        .card-header {
            background-color: black;
            color: #fff;
            border-radius: 10px 10px 0 0;
        }

        .card-body {
            padding: 30px;
        }

        .form-group label {
            font-weight: bold;
        }

        .btn-primary {
            background-color: black;
            border: none;
        }

        .btn-primary:hover {
            background-color: green;
        }
    </style>

         <div class="container" style="margin-top:100px;padding-left:250px;">
            <div class="card border border-dark">
                <div class="card-header text-center">
                    <h4>Change Password</h4>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="current_password" class="form-label">Current Password</label>
                            <input type="password" class="form-control" id="current_password" name="current_password">
                        </div>
                        <div class="mb-3">
                            <label for="new_password" class="form-label">New Password</label>
                            <input type="password" class="form-control" id="new_password" name="new_password">
                        </div>
                        <div class="mb-3">
                            <label for="confirm_password" class="form-label">Confirm New Password</label>
                            <input type="password" class="form-control" id="confirm_password" name="confirm_password">
                        </div>
                        <button type="submit" class="btn btn-primary">Change Password</button>
                    </form>
                </div>
            </div>
        </div>
    
    
{% endblock %}

app/templates/mechanic_req_list.html
{% extends 'mechanic_home.html' %}
{% block  mechanic %}
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<!-- Add Bootstrap JavaScript (optional, but required for certain features) -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<style>
    body{
        background: rgb(241, 239, 240);
        background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(76, 76, 77) 100%);
    }
    .card {
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
}

.card-title {
    font-size: 1.25rem;
}

.btn {
    padding: 0.5rem 1.5rem;
}


</style>
   <div class="container mt-5">
    <div class="form-control border-0 p-5 bg-white bg-opacity-50 mb-3" action="" style="height: fit-content;">
        <div>
            <h1  class="text-center ">Requests Made By User</h1>
            <div class="row mt-4 " style="margin-left: 100px;" >
                {% for request in requests %}
                <div class="col-md-5 mb-3">
                    <div class="card">
                        <div class="card-body">
                            <div class="row mb-3">
                                <div class="col-4">
                                    <img src="{{request.user.profile_pic.url}}" alt="" height="100px" width="150">
                                </div>
                                <div class="col mt-4">
                                    <h5 class="card-title text-center" style="font-family: 'Times New Roman', Times, serif;font-weight: bolder;">{{ request.user.name }}</h5>
                                </div>
                            </div>
                            <p>Description : {{request.discription}}</p>
                            <p>Phone : +91 {{request.phone}}</p>
                            <p>Location : {{request.location}}</p>
                            <div class="row">
                                {% if request.status == 'completed' and  request.bill_set.exists %}
                                  <p class="bg-success text-center text-light" style="border-radius: 0.25rem;padding: 10px;">Completed</p>
                                {% elif request.status == 'Payment Pending' %}
                                        <p class="bg-warning text-center text-light" style="border-radius: 0.25rem;padding: 10px;">Payment Processing</p>

                                {% endif %}
                                
                                <div class="col">
                                    {% if not request.bill_set.exists %} <!-- Check if bill is not created -->
                                    <form action="{% url 'create_bill_payment' request.id %}" method="post">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-block btn-info ">Create Bill</button>
                                    </form>
                                    {% endif %}
                                </div>
                            </div>
                         
                           
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        {% if messages %}
            {% for message in messages %}
                alert('{{ message }}');
            {% endfor %}
        {% endif %}
    });
  </script>
{% endblock %}